name: CI

on: [push, pull_request]

jobs:
  lint-shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Runs shell script static analysis
        run: |
          sudo apt-get install shellcheck
          ./run-tests.sh --check-shellscript

  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install project dependences
        run: |
          sudo apt-get update -y
          gem install awesome_bot
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint docs
        run: ./run-tests.sh --check-docstyle

      - name: Build docs
        run: ./run-tests.sh --build-docs
